### ISSUE TITLE
_container is best as a subclass of dict

### ISSUE THREAD

**Issue by mhosken** [silnrsi/pysilfont#42]
_container really needs the full capabilities of dict() and so is most easily implemented as a subclass of dict(). An alternative would be to use collections.defaultdict. This requires some refactoring. It's also probably best if there is only one _container implementation and have _UElement based on ET._container.

**Comment by bobh0303** [comment]
Not that I'm agin' it, but perhaps you could explain why it "really needs" this?

**Comment by DavidRaymond** [comment]
It was deliberately done to avoid having the full capabilities of dict().  For example, it's useful to access glyphs  using `glyph = Ulayer[<glyphname>]`, but adding a glyph should be done using `Ulayer.addGylph()` since that does other necessary work like checking that the .glif file name is unique.  Making _container a dict() would allow `Ulayer[<glyphname>] = newglyph`, which would not be desirable (without implementing __setitem__ etc in every object based on _container.

**Comment by DavidRaymond** [comment]
Closed since this is by design
