### ISSUE TITLE
-h -d isn't documented in the -h help

### ISSUE THREAD

**Issue by mhosken** [silnrsi/pysilfont#46]
-h should have something about using -h -d to get possible -p values. In addition, it really should list all the -p values.

**Comment by DavidRaymond** [comment]
I don't understand this.  -h does document -d, and you can't use "-h -d to get possible -p values."

I'm not sure listing all -p values would b a good idea, since there are currently 17 of them and likely to increase.  They are documented in parameters.md.  Perhaps there should be some way to list them at the command line - though most users would probably prefer to look at well-formatted markdown rather than plain text for large amounts of information.

**Comment by mhosken** [comment]
App -h -d lists parameter defaults. It's a magic sequence from what I can
see. Just asking that -h -d be documented in -h.

**Comment by DavidRaymond** [comment]
Actually you just need -d, and that is documented in -h.

I think the help for -p should be changed from
```
-p PARAMS, --params PARAMS
                        Other parameters
```
to
```
-p PARAMS, --params PARAMS
                        Other parameters - see parameters.md for details
```
or similar
