### ISSUE TITLE
Handling missing xHeight

### ISSUE THREAD

**Issue by mhosken** [silnrsi/pysilfont#51]
If xHeight is missing, then either psfufo2ttf or psfnormalize should treat it as 0.

**Comment by jvgaultney** [comment]
It's silly that we have to accommodate xHeight at all for non-Latins, however ufo2ft seems to require it (see metadata spreadsheet - link not given since it's a private doc at the moment). I wouldn't set it to 0 though, as in some workflows (AFDKO?) that could mess up hinting pretty badly. I'd suggest that this should be handled in checkfix, and set to 60% of the ascender if missing. I've updated the spreadsheet accordingly.

**Comment by DavidRaymond** [comment]
Fixed in https://github.com/silnrsi/pysilfont/commit/4e01b26c14e749c7ee0af48de2abfe237e03199a
