### ISSUE TITLE
psfcheckglyphinventory should process public.skipExportGlyphs

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/pysilfont#79]
Glyphs mentioned in `public.skipExportGlyphs` :
- should _not_ be reported as missing from `glyph_data.csv`.
- should be reported if they _are_ in `glyph_data.csv`

**Comment by jvgaultney** [comment]
I'd disagree. The glyph_data.csv is intended as a source of additional info for every glyph in the UFO - *not* the built fonts. If we wish the glyph_data to somehow reflect or represent whether something should be in `public.skipExportGlyphs` then I suggest we add a column to the csv that indicates whether a glyph is to be exported or not. Then we can have a separate script (psfsetexports - similar to psfsetpsnames) that will update that lib.plist key from the CSV. Preflight can then use that file. So we could simplify the process of marking a glyph as non-exported by just twiddling that record in the CSV rather than directly editing the lib.plist.

**Comment by bobh0303** [comment]
Ok that's fine.  Is there any reporting based on the list of public.skipExportGlyphs that might be useful?

**Comment by bobh0303** [comment]
Issue withdrawn.
