### ISSUE TITLE
Pull out feax preprocessing into separate module

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/pysilfont#88]
To make it easier to integrate feax preprocessing into a variety of tools (fonttools, Glyphs, etc.) it would be better to have the functions of psfmakefea pulled out into an independent module, with UFO reading done through defcon/ufoLib2.

It could then be made into a ufo2ft filter that would get automatically applied. The relative reference to the external .feax file could be placed in a key in a UFO's lib.plist in the same fashion as the parameters for other ufo2ft filters.

**Comment by bobh0303** [comment]
Would need to handle options in addition to the master feax file, including 
```
[-c CLASSFILE] 
[-L LIGMODE] 
[-D DEFINE] 
[--classprops] 
[--omitaps OMITAPS]
```

**Comment by bobh0303** [comment]
Also, this might be an opportunity to resolve #86 if not already done.

**Comment by n7s** [comment]
See [feax repo](https://github.com/silnrsi/feax)

**Comment by bobh0303** [comment]
> Would need to handle options in addition to the master feax file, including
> 
> ```
> [-c CLASSFILE] 
> [-L LIGMODE] 
> [-D DEFINE] 
> [--classprops] 
> [--omitaps OMITAPS]
> ```

This is done:
```
❯ makefea --help
usage: makefea [-h] -i INPUT [-o OUTPUT] [-c CLASSFILE] [-L LIGMODE] [-D DEFINE] [--classprops] [--omitaps OMITAPS]
               [--psfCompatible] [-q] [-l LOG]
               infile

positional arguments:
  infile                Input UFO or file

options:
  -h, --help            show this help message and exit
  -i INPUT, --input INPUT
                        Fea file to merge
  -o OUTPUT, --output OUTPUT
                        Output fea file
  -c CLASSFILE, --classfile CLASSFILE
                        Classes file
  -L LIGMODE, --ligmode LIGMODE
                        Parse ligatures: last - use last element as class name, first - use first element as class
                        name, lastcomp, firstcomp - final variants are part of the component not the whole ligature
  -D DEFINE, --define DEFINE
                        Add option definition to pass to fea code --define=var=val
  --classprops          Include property elements from classes file
  --omitaps OMITAPS     names of attachment points to omit (comma- or space-separated)
```

**Comment by bobh0303** [comment]
Note: 

The boundingbox calculation currently in `psfmakefea` incorrectly ignores components and also can come up with slightly different results for contours that do not have on-curve points at the extrema. Unfortunately, the feax calculations for at least two projects (Padauk and Kanada) depend on these miscalculations so we can't fix psfmakefea now. 

`makefea` uses a method from `ufolib2` that draws the glyph in question and takes the bounding box from the results, thus correcting both of psfmakefea's miscalculations.

In order to support projects that currently depend on psfmakefea's algorithm until they can be updated, we have introduced a `--psfCompatible` command-line option to `makefea` that mimics the algorithm from psfmakefea.

**Comment by bobh0303** [comment]
We've deployed the new [feax repo](https://github.com/silnrsi/feax) and are using it in smith;  `psfmakefea` is now deprecated.
