### ISSUE TITLE
`openTypeHeadCreated` should not be updated during normalization

### ISSUE THREAD

**Issue by rimas-kudelis** [silnrsi/pysilfont#94]
According to [OpenType spec](https://learn.microsoft.com/en-us/typography/opentype/spec/head), this header has two very similar fields: `created` and `modified`. Their semantic meaning is not explained, but I think it's logical to assume that `created` is supposed to store the original creation date of the font, whereas `modified` would store the timestamp of the latest update to the font.
In the [UFO format specification](https://unifiedfontobject.org/versions/ufo3/fontinfo.plist/#opentype-head-table-fields), there's are several notes under the OpenType head Table Fields table, of which the following are relevant: 
> 5. `created` can be calculated by subtracting the _12:00 midnight, January 1, 1904_ (as specified in the head table documentation) from the date stored at `openTypeHeadCreated`.
> 6. `modified` should be set by the authoring tool.

Currently `psfnormalize` overwrites the `openTypeHeadCreated` date whenever it fixes something. I don't think it should do this.

**Comment by rimas-kudelis** [comment]
Also, same should also apply to the value of `creator` in `metainfo.plist`. `psfnormalize` currently replaces the value of that field with `org.sil.scripts.pysilfont`, but that field is optional, so it would be just as easy to remove it instead. A normalizer that overwrites creator's name with its own is a bit full of itself, IMO.

**Comment by alerque** [comment]
Yes I agree. Even further some tooling that touches `creator` either replaces or appends itself *with version info*. This can be useful info, but it actively works against the idea of normalization and even being able to compare different versions. Dates, version numbers, and anything else that can change but *should not* automatically mean changes to the underlying data should not touch the underlying data just for the sake of it.

The software world has started to realize this with the push for reproducible build artifacts, but the font world is a bit behind in understanding the value in reproducibility.

**Comment by jvgaultney** [comment]
Regarding the `creator` key in `metainfo.plist`: The [UFO3 spec](https://unifiedfontobject.org/versions/ufo3/metainfo.plist/) says this should be "The application or library that created the UFO." Because normalization effectively recreates the UFO to match pysilfont's default style, it is important that the metainfo declare that pysilfont was the `creator`. Since every app that writes or created UFOs has a different style, this can sometimes be useful for knowing which app wrote this version of the UFO. In this case pysilfont is closely following the intent of the spec.

**Comment by jvgaultney** [comment]
Regarding `openTypeHeadCreated`: Keep in mind that pysilfont normalization only reads and writes the UFO and has no reference to OpenType data that may be in the `head` table of OpenType fonts (.ttf or .otf). The numbered notes below the section you link to about "OpenType head Table Fields" refer to specific OpenType `head` values and how they can be synthesized, in some cases from the UFO attributes.

In normalization pysilfont only has access to the `openTypeHeadCreated` field in the UFO, not any data that may be in OpenType '`head' fields (`created' or `modified`). Since there is no distinction between creation and modifications dates in the UFO it cannot set those. The only sensible action for pysilfont is to change the date to match when that particular version of the UFO was changed (normalized).

Setting the values of the `created` and `modified` OpenType `head` fields is completely up to the tool that reads the UFO and produces a .ttf or .otf file. The `psfufo2ttf` command (which is completely separate from normalization) calls on the industry standard [ufo2ft](https://github.com/googlefonts/ufo2ft) tool to do that.  Of course that tool only sees the UFO source, which contains only the `openTypeHeadCreated` value. It cannot set the `created` or `modified` values to anything but the value in the UFO.

I hope that clarifies the issue and shows that pysilfont is doing the right thing.

**Comment by rimas-kudelis** [comment]
> Regarding the `creator` key in `metainfo.plist`: The [UFO3 spec](https://unifiedfontobject.org/versions/ufo3/metainfo.plist/) says this should be "The application or library that created the UFO." Because normalization effectively recreates the UFO to match pysilfont's default style, it is important that the metainfo declare that pysilfont was the `creator`. Since every app that writes or created UFOs has a different style, this can sometimes be useful for knowing which app wrote this version of the UFO. In this case pysilfont is closely following the intent of the spec.

I get what you're saying, but by that logic whenever I edit any file in any application, that application would become the creator. It's true, some apps will mark themselves as the ones that last saved the file, but I would expect better from `psfnormalizer`, especially considering that UFO is a source format, and one of the main points of normalization is to reduce the number of merge conflicts.

You could reasonably argue that hardcoding that value to something specific reduces conflicts, but at least I would prefer it if `psfnormalizer` simply removed this unnecessary field rather than make it pretty meaningless, because I don't think anyone really *creates* fonts using `org.sil.scripts.pysilfont`, they only *process them* (or, in this case, normalize them) using the lib instead. As for that string being useful for knowing which app was used for normalization, well, that's true, but I'd say it's still quite a stretch. Ideally, normalizers should be configurable, so that I could easily move from one to the other if I wanted to (which I can't do at the moment, for example, because `psfnormalize` and `ufonormalizer` decided on two different line indentation styles, and none of them seems to be configurable in that regard).

> In normalization pysilfont only has access to the `openTypeHeadCreated` field in the UFO, not any data that may be in OpenType '`head' fields (`created' or `modified`). Since there is no distinction between creation and modifications dates in the UFO it cannot set those. The only sensible action for pysilfont is to change the date to match when that particular version of the UFO was changed (normalized).

I strongly disagree. The only sensible action would be to leave that field untouched, since there's nothing in it that could be sensibly _normalized_ (unless the value itself were invalid somehow).

> Setting the values of the `created` and `modified` OpenType `head` fields is completely up to the tool that reads the UFO and produces a .ttf or .otf file. The `psfufo2ttf` command (which is completely separate from normalization) calls on the industry standard [ufo2ft](https://github.com/googlefonts/ufo2ft) tool to do that. Of course that tool only sees the UFO source, which contains only the `openTypeHeadCreated` value. It cannot set the `created` or `modified` values to anything but the value in the UFO.

The way I read UFO3 spec, that tool is supposed to "calculate" itself the `modified` value to use. And it does exactly that:
https://github.com/googlefonts/ufo2ft/blob/5fd168e65a0b0aa25298ad970546c3ab99d910c6/Lib/ufo2ft/outlineCompiler.py#L351-L356

Furthermore, again, one of the main points of normalization is to reduce the number of merge conflicts. Changing the value of this field each time there's something to normalize serves exactly the opposite.

**Comment by jvgaultney** [comment]
> I get what you're saying, but by that logic whenever I edit any file in any application, that application would become the creator. It's true, some apps will mark themselves as the ones that last saved the file, but I would expect better from `psfnormalizer`, especially considering that UFO is a source format, and one of the main points of normalization is to reduce the number of merge conflicts.

Sorry, but the UFO3 spec is clear on this, and makes good sense. As a developer and designer I want to know what tool last touched and normalized the UFO. It would actually be nice to have more information in the UFO: The origin app and initial data as well as the last modification date and what app made that modification (following the OpenType spec). I suggest you file an issue with with UFO spec itself.

As a point of reference, other UFO editing tools reset the field. Robofont, which uses the ufoLib library to write out UFOs sets it to `com.github.fonttools.ufoLib`. We are following the industry precedent. You are, of course, welcome to try and change that precedent, however this is not the place to do that.
 
> You could reasonably argue that hardcoding that value to something specific reduces conflicts, but at least I would prefer it if `psfnormalizer` simply removed this unnecessary field rather than make it pretty meaningless...

It is certainly useful to us, and is much better than having no info. Again, this is following what other UFO tools do.

> Ideally, normalizers should be configurable, so that I could easily move from one to the other if I wanted to (which I can't do at the moment, for example, because `psfnormalize` and `ufonormalizer` decided on two different line indentation styles, and none of them seems to be configurable in that regard).

Ours was the first normalizer. ufonormalizer came later and made different normalization choices. Ideally the UFO spec would declare a canonical normalization that we could both follow, but since it doesn't we've had to make up our own. It would then be nice if there were separate `lastNormalized` and  `normalizationStyle' fields. But in the absence of such fields  the `openTypeHeadCreated` and `creator` need (in our opinion) to reflect the last time the UFO was changed in any way.

> I strongly disagree. The only sensible action would be to leave that field [openTypeHeadCreated] untouched, since there's nothing in it that could be sensibly _normalized_ (unless the value itself were invalid somehow).

Normalization can, and does, substantially change the UFO in ways that can affect how it is interpreted by some tools. Because of that there needs to be *some* indication in the UFO itself of the last time it was changed. Because those files are often authored, mondified, and distributed outside of a source control environment you cannot rely on things like git metadata to track the last change date.

If someone sends me a UFO I want to be able to see when it was last changed, and by what tool.

> > Setting the values of the `created` and `modified` OpenType `head` fields is completely up to the tool that reads the UFO and produces a .ttf or .otf file. The `psfufo2ttf` command (which is completely separate from normalization) calls on the industry standard [ufo2ft](https://github.com/googlefonts/ufo2ft) tool to do that. Of course that tool only sees the UFO source, which contains only the `openTypeHeadCreated` value. It cannot set the `created` or `modified` values to anything but the value in the UFO.
> 
> The way I read UFO3 spec, that tool is supposed to "calculate" itself the `modified` value to use. And it does exactly that: https://github.com/googlefonts/ufo2ft/blob/5fd168e65a0b0aa25298ad970546c3ab99d910c6/Lib/ufo2ft/outlineCompiler.py#L351-L356

Yes, you are correct. However it chooses the current time to do that. It cannot get that info out of the UFO (as it doesn't exist).

**Comment by alerque** [comment]
> We're following industry precedents.

Then why normalize? The industry precedent is to have every tool write UFO compliant (ish) files that substantively represent the same font data but with piles of different meta data stuffed in. As a result the industry precedent is that two people cannot easily collaborate on the same sources asynchronously because industry standard tooling universally made choices that do not play nice with VCS. These days VCS is more important and has much richer data than whatever meta data fields each app wants to stuff them with.

**Comment by jvgaultney** [comment]
> > It would then be nice if there were separate `lastNormalized`
> 
> Really? What do you think the point of normalization is? Because this suggests you have a completely different concept of what is even being accomplished.

What UFO normalization really does (by all UFO tools) is not really true normalization, as that would require a canonical concept of what 'normal' means. We end up creating different 'flavours' of UFO and our tools all 'normalize' to our preferred flavour.

> How would a normalizer that did what you suggest _not_ became a blocker if two people worked on a font and submitted PRs touching two totally different glyphs, but both people normalized when they were ready to submit?

That is a practical limitation of having to live with multiple concepts of 'normal'. That scenario can be frustrating, but at least you know that someone else has been editing and you should check that your flavours are compatible. If that is a regular pain for you, then you can either agree among you to not commit the `openTypeLastCreated` change to the UFOs, or you can add a normalization option to pysilfont to not change that attribute.

**Comment by rimas-kudelis** [comment]
> > How would a normalizer that did what you suggest _not_ became a blocker if two people worked on a font and submitted PRs touching two totally different glyphs, but both people normalized when they were ready to submit?
> 
> That is a practical limitation of having to live with multiple concepts of 'normal'. That scenario can be frustrating, but at least you know that someone else has been editing and you should check that your flavours are compatible.

I think this specific point wasn't about flavours. It was about changing the "created" date by the normalizer, which has no relation to whatever "flavour" or "normal" you use. Unless you're saying that the decision whether to change date is part of the "flavour" as well.

> If that is a regular pain for you, then you can either agree among you to not commit the `openTypeLastCreated` change to the UFOs, or you can add a normalization option to pysilfont to not change that attribute.

It's difficult to agree not to commit something, because it's easy to overlook this date change and commit it nevertheless. Unless you add a git hook, or another normalizer on top, or, like you suggested, propose a patch to `psfnormalizer`. Welp, I'm actually glad you're at least open to that scenario.

**Comment by alerque** [comment]
> What UFO normalization really does (by all UFO tools) is not really true normalization, as that would require a canonical concept of what 'normal' means. We end up creating different 'flavours' of UFO and our tools all 'normalize' to our preferred flavour.

I don't think this is correct. Of course there is "no true Scotsman", but that's not the point. The point is to use a tool that takes any and all valid input and elides away stylistic and other non-meaningful differences and deterministically produces a canonical output that can be compared apples-to-apples with any other files that have been similarly processed such that the *substantive* differences are shown and any differences in the way other tools wrote the data that do not need to affect the output are ignored.

If you think "normalizing" is just about preferred style of indentation in XML then in my view that's just a code formatter not really normalization. And I think even given the limitations of UFO, we can achieve close to deterministic normalized usage to that it is actually practical to collaborate where contributions are asynchronously created using different tooling.

Whether a different tool like `ufonormalizer` makes different stylistic choices is irrelevant, what I want is for a project to be able to spec their normalizer of choice and then contributors to be able to work on the project using any *other* tooling of their choice while not creating merge conflicts because they can normalize to project specs when they are ready to commit.

**Comment by alerque** [comment]
> then you can either agree among you to not commit the `openTypeLastCreated` change to the UFOs

I know how to setup Git tooling to not automatically show this as an unstagged changed, but I'd be willing to be north of 99% of people working on fonts have no idea how to do that. Do you?

Most Git tooling does not support it, only file-wise overrides using `.gitignore` are supported, not linewise ones. A large part of the point of a normalizer is to handle stuff like this for users so they can collaborate without needing to setup clean/smudge filters on their UF files!

**Comment by jvgaultney** [comment]
> I know how to setup Git tooling to not automatically show this as an unstagged changed, but I'd be willing to be north of 99% of people working on fonts have no idea how to do that. Do you?

We tend to actually review changes using our git clients and can trivially discard such individual changes.

**Comment by jvgaultney** [comment]
We could go on arguing about this, but we're not going to change the default way that pysilfont handles these values.

We're also unlikely to ourselves expand the options that we support (multiple normalization flavours, "pure" command-line flags, date change options). We have limited staff and often struggle with addressing even our own needs, with a long list of pysilfont enhancements that remain in the queue. Even if we did have the capacity we haven't heard from others that our handling of these fields should be changed or enhanced, even though we've been doing normalization for many years.

Of course we would be open to community contributions to make enhancements! If you or others in the community wanted to enhance pysilfont to behave how you want it to, the most easily-acceptable way would be for you to submit a pull request that adds a command-line parameter - see [Pysilfont parameters](https://github.com/silnrsi/pysilfont/blob/master/docs/parameters.md). Such parameters can then be set in individual projects.

**Comment by rimas-kudelis** [comment]
@jvgaultney, thanks for the Parameters link! I was pretty certain that I had seen a normalizer that was configurable with regards to indentation, but somehow I missed that bit when skimming the parameters doc at a later point. I'm also glad that configuration can already be stored in `lib.plist` (albeit I wonder if using arbitrary tags like `<indentIncr>` and `<glifElemOrder>`  instead of a nested dictionary with keys and values is the correct thing to do).

**Comment by rimas-kudelis** [comment]
With my patch above, and the following bit in lib.plist, `openTypeHeadCreated` will not be touched by `psfnormalize`:
```xml
  <key>org.sil.pysilfontparams</key>
  <array>
    <updateTimestamps>True</updateTimestamps>
  </array>
```

**Comment by rimas-kudelis** [comment]
@jvgaultney, could you tell me what does the following default value that `psfnormalizer` sets do:

```xml
  <key>com.schriftgestaltung.customParameter.GSFont.disablesLastChange</key>
  <true/>
```

**Comment by jvgaultney** [comment]
Glyphs+glyphLib by default sets a 'last change' timestamp on many files in a UFO that it not helpful and causes a lot of unnecessary file changes. We set this to disable this timestamping.

**Comment by rimas-kudelis** [comment]
Ah ,okay, thanks again!

**Comment by rimas-kudelis** [comment]
@jvgaultney, while skimming the UFO spec again, I just stumbled upon [this](https://unifiedfontobject.org/versions/ufo3/lib.plist/#publicopentypeheadmodified). Apparently, there is a more-or-less standard way to control the value of the OpenType `modified` header via an entry in `lib.plist`.

I wonder why SIL is not using that instead of updating the supposed created date with each minor change?

**Comment by jvgaultney** [comment]
That's a relatively recent addition to the spec (2023). Our tools and processes have been around a lot longer than that. The UFO3 spec tends to evolve gradually, and new public keys are added to lib.plist once in a while. No one is required to use them - they are optional. We don't modify our tools to use them unless we see a good need to do so.

There is also the issue of external tool support. We might choose to use a new fontinfo.plist or lib.plist key, but if some of the external tools we use (glyphsLib, Robofont, fonttools) don't support it (and they tend not to keep up with the spec changes) then we can't reasonably use it. We don't have the capacity to test and support every new addition to the spec.
